### PR TITLE
Fix Microsoft Edge detection

### PR DESCRIPTION
**Pull request by ymgsmz**
The regex extended to be able to detect new versions of Microsoft Edge's User-Agents

### CODE REVIEW

**Comment by oalders** [comment]
Thanks very much for this @ymgsmz!  The Travis tests are broken.  I'll have to look into those.  When running this manually, I get:

```sh
BAIL_ON_FAIL=1 prove -lvr t

...

# Subtest: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.137 Safari/537.36 Edg/80.0.361.62
    ok 1 - browser: edge
    ok 2 - browser_string: Edge
    ok 3 - engine: edgehtml
    ok 4 - engine_beta:
    ok 5 - engine_string: EdgeHTML
    ok 6 - os: windows
    ok 7 - os_string: Win10.0
    ok 8 - robot: undef
    not ok 9 - engine_version: 13.10586

    #   Failed test 'engine_version: 13.10586'
    #   at t/01-detect.t line 98.
    #          got: 537.36
    #     expected: 13.10586
Bailout called.  Further testing stopped:  Test failed.  BAIL OUT!.
```

**Comment by ymgsmz** [comment]
Oh yea, It was my wrong, let me fix it.

**Comment by oalders** [comment]
Did you close this accidentally?

**Comment by ymgsmz** [comment]
yes,
I fixed the problem and the test's expectation result, it works fine in my manual test.

**Comment by oalders** [comment]
Thanks very much @ymgsmz!

**Comment by oalders** [comment]
This has now been released to CPAN.

**Comment by ymgsmz** [comment]
Sure, Thank you

**Pull request merged**
