### PR TITLE
Improve detection for MS Edge

### PR DESCRIPTION
**Pull request by zakame**
Support mobile releases of MS Edge for iOS and Android, and in
particular, relax checking for the browser identifier match, as some
versions of Edge for iOS put this identifier in the middle, rather than
the end, of the UA string.

### CODE REVIEW

**Comment by ymgsmz** [comment]
Does this change also support user-agent of Edge on different Linux os and distros?  or we should wait for launching a stable version of Edge for Linux?

**Comment by zakame** [comment]
Nothing on Linux support just yet until MS makes an official release, though I don't expect any big change on the Linux user-agent string.

**Comment by oalders** [comment]
https://metacpan.org/release/OALDERS/HTTP-BrowserDetect-3.27

**Comment by zakame** [comment]
Thanks too @oalders ! :tada:

**Pull request merged**
