### PR TITLE
Add some browsers and robots, fix issue#93 and issue#96

### PR DESCRIPTION
**Pull request by andrewmoise**
I added detection of BrowseX and Silk, detected a bunch more robots as robots, and fixed some open issues.

### CODE REVIEW

**Comment by oalders** [comment]
Thanks!

**Comment by oalders** [comment]
Also, feel free to add important changes to the Changes file.  That makes it a bit faster to merge + release. :)

**Comment by oalders** [comment]
I've recently added a perltidy config to the repo, so you can also run that on your commits to keep the formatting consistent.

**Comment by andrewmoise** [comment]
Okay, sounds good; I'll do that in the future. I do have a few other changes I'd be interested to make; off the top of my head:

* Finish the os_version interface and publicize it
* Update the engine detection (if it were me I would make it report Blink, Gecko, iCab, KHTML, Netfront, Presto, Trident, and Webkit, and the version of each if possible)
* Formally deprecate the version interface that includes the bug-compatible Safari versions
* Remove some other bug compatibility (e.g. reporting "Linux" for Android devices)
* Add a "lib" test for things like curl, AppleWebKit, wget, puf, etc.
* Add a "phone" test for phones, to let people avoid the philosophical conversation of what constitutes a mobile device

If those all sound good to you I'll add them to the TODO file and start working on them at some (probably intermittent) pace, but let me know what you think about it.

I was looking over some of the other issues in the DB, and I ran across your conversation with Neil Bowers from a few years ago. Certainly I think perl should have one library that correctly interprets a broad range of user agents with some reasonable speed -- did the effort to combine the two libraries ever go anywhere?

I'm curious to rerun the same comparison between libraries that he did in 2012, although I would be basing it on entries from my own log, so that it's a comparison based on what people (i.e. me :-) ) commonly run across in the real world.

**Comment by oalders** [comment]
That all sounds good to me. Please feel free to add it to TODO.  @neilbowers and I both got distracted by other things, but I think it's still a good idea.  I'm not sure what new UserAgent parsers have emerged in the meantime as well.

**Pull request merged**
