### PR TITLE
add Microsoft Windows 10/Windows Phone 10 Edge Browser.

### PR DESCRIPTION
**Pull request by ktat**
add MS Windows 10/Windows Phone 10. new browser Edge support.

This patch makes its browser name and its engine name as same name "edge".
Is it no problem?

### CODE REVIEW

**Comment by oalders** [comment]
Great! Thanks for this.  Is the actual engine name Edge or EdgeHTML? https://en.wikipedia.org/wiki/EdgeHTML  If it's the latter, we should probably use `edgehtml` as the engine.  @dougwilson any thoughts on this?

**Comment by ktat** [comment]
It seems right name. I've adopted it.

**Comment by oalders** [comment]
:+1:

**Comment by dougwilson** [comment]
Yep, I have no objections to this PR's contents :) I looked at it last night just to be sure it's not getting any of the `ie` flags set, which would be bad.

**Comment by oalders** [comment]
@dougwilson++

**Comment by oalders** [comment]
New release on its way to CPAN.

**Comment by ktat** [comment]
I don't know Edge browser compatibility with IE, yet.
I cannot say whether ie flags are useful or not.

For example, if you want to detect browser for IE plugin download page, it is not good case.
Because Edge is not compatible with IE plugin.

**Comment by dougwilson** [comment]
Edge is a very different browser from IE; UA detectors should not detect it as IE.

**Comment by ktat** [comment]
got it.

**Comment by ymgsmz** [comment]
@oalders It seems the new versions of Microsoft Edge's known as different UA, the Edge detection problem still exists (in case of Microsoft Edge on Windows 10),
so in my PR, the problem has been solved.

**Pull request merged**
