### PR TITLE
Robot versions and misc fixups

### PR DESCRIPTION
**Pull request by andrewmoise**
Here's a first cut at robot versioning. It seems to work for most robots. There are also a lot of other miscellaneous changes and new things detected / fixed (detailed in Changes) bringing what I've pushed up to date with what I'm using locally. Let me know if you see any issues or adjustments that need to be made.

Cheers,
Andrew

### CODE REVIEW

**Comment by oalders** [comment]
Thanks for this.  I'll need some time to review all the changes.  :)

**Comment by andrewmoise** [comment]
Makes sense. My thinking was to get it all out of the way but if you want me to break future work into more separate pull requests let me know.

**Comment by oalders** [comment]
Oh, I'm not complaining about the size of the merge.  I'm just saying I may not get to it _tonight_.  :)

**Comment by oalders** [comment]
Finally took the time to give this a proper look.  Thanks so much.  I appreciate you updating the Changes file.  Saves me a lot of time. :)

**Comment by oalders** [comment]
Also added you to the collaborators for this repo.

**Comment by andrewmoise** [comment]
I will use my powers only for good. :-)

**Pull request merged**
