### PR TITLE
Kindle Fire broadened detection

### PR DESCRIPTION
**Pull request by andrewmoise**
This fixes issue #129 and adds a test for that style of Kindle Fire UA.

### CODE REVIEW

**Comment by oalders** [comment]
Looks good.  Could you resolve the merge conflict?

**Comment by oalders** [comment]
rebased and force-pushed.

**Comment by andrewmoise** [comment]
Excellent; sorry for me not fixing this. I've been meaning to but I had a hardware issue with my Linux machine that still isn't resolved.

**Comment by oalders** [comment]
The conflict was in `Changes`, so it was trivial to sort out.  Thanks for all of your work on this. :)

**Pull request merged**
