### PR TITLE
Add BingPreview to bot checker

### PR DESCRIPTION
**Pull request by j-waters**
The BingPreview bot wasn't being detected by the robot checker

### CODE REVIEW

**Comment by oalders** [comment]
Thanks for this!  If you run the tests locally, you'll see that one test is failing.

**Comment by j-waters** [comment]
Sorry, made the classic mistake of thinking a fix was too trivial to add tests! The issue was a test user agent that belonged to the BingPreview bot not being labeled as such.

**Comment by oalders** [comment]
Thanks @j-waters!

**Comment by oalders** [comment]
New release is on its way to CPAN.

**Pull request merged**
