### PR TITLE
Versions as strings

### PR DESCRIPTION
**Pull request by andrewmoise**
Update documentation about version accessors

### CODE REVIEW

**Comment by oalders** [comment]
Thanks!  Dist::Zilla will update the README. Just a nitpick, but could you delete the merge commit and force-push?

**Comment by andrewmoise** [comment]
Sure, done (I think). Please forgive any missteps with git and let me know if I should be doing anything else differently; I'm not too familiar with git and I'm totally unfamiliar with how people generally do things on github. :-)

**Comment by oalders** [comment]
:+1:  Basically `git pull` will do a fetch + merge, but `git pull --rebase` will do a fetch + rebase, which will result in a cleaner history for pull requests.  :)

**Comment by andrewmoise** [comment]
Ah, makes sense, thanks!

**Pull request merged**
