### PR TITLE
Make things faster, also fix issue #85

### PR DESCRIPTION
**Pull request by andrewmoise**
I'm working on a log file analyzer, and when running on a decent-size log file it takes 5 minutes to parse the log, of which 1 minute is spent in HTTP::BrowserDetect. That's too much :-). I spent some time making the obvious speedups I could see; they're described in more detail in the commits, but it reduced the 60 seconds it was spending on browser detection down to 30 seconds.

These are pretty extensive changes, so I wouldn't expect you to merge them immediately and without question, but I actually think they're good changes. In addition to making things faster, they make things more straightforward. We used to run the OS and robot tests, then the browser tests, then the OS and robot tests *again*, with a tiny number of them having different results based on the browser tests, and I think sometimes even a test would be set to 1 and then set to 0 later on because a special case was detected. Some of that is removed now, and some is highlighted where it takes place even if it's still around. We only run the OS and robot tests once.

Also, I finally fixed issue #85, which is great for me because I get to stop looking at the warnings, and I added a test appropriate to that case.

Thanks in advance, again let me know anything I should be doing different (or anything I did wrong) as I'm not too familiar with git/github.

### CODE REVIEW

**Comment by oalders** [comment]
Thanks for this!  I'm going to need a quiet moment to review all of the changes. :) I think we could probably save even more time by switching to Moo and making pretty much everything load lazily, but I don't have the bandwidth for that right now, so this is doubly appreciated.

**Comment by dougwilson** [comment]
The fact that all the existing detection tests still pass (assuming they did since you didn't modify them) is already a good sign, imo :)

**Comment by oalders** [comment]
>  the vast majority of the time is spent in _test

Right.  We're testing for a whole pile of things that nobody is necessarily asking for or cares about.  My guess would be that in most cases people don't want to call 50 methods on the object.  If we just did the bare minimum and did the rest on demand, that could likely speed things up.  (I should note that I haven't done _any_ profiling).

**Comment by andrewmoise** [comment]
Oh, I get it. Yes, it would be better to test for those things only when the user asks for them (or when it's necessary to test for them to figure out browser and version). Also doing it that way would further remove some more of the mysterious behavior of the current code.

I posted the results of my profile as they pertain to HTTP::BrowserDetect. You'll have to download them and view them locally, because I'm lazy:

https://github.com/andrewmoise/browserdetect-profile

The short answer is, I agree that pulling most of the tests into methods instead of doing all the tests in _test would be beneficial. I think that's actually better than my approach.

I'm not sure that Moo helps that much. The setup of methods (line 243-245 in the profile) takes negligible time, then time spent actually inside the accessor is incredibly costly (25 seconds, the vast majority of the runtime) -- but that'll still be true if we're using Moo (and conversely it'll stop being true if we stop calling the methods so much, whether or not we use Moo). No? Or have I misunderstood?

Want me to take a quick crack at speeding it up that way instead?

**Comment by oalders** [comment]
I guess it's pretty obvious where all the time is being spent.  :)  Nice to see the evidence!

It would be nice to use Moo more because it makes things cleaner and we could easily take advantage of type checking with Type::Tiny at some point if we wanted to, keeping in mind that could slow things down a bit.  Also, it would make the lazy loading quite easy.  I think the gain in speed would be from doing less work up front, but not from Moo itself.  It would also be great to make the internals of HTTP::BrowserDetect less funky.

Using Moo would likely mean we'd be breaking _self_or_default(), but I'm OK with breaking the behaviour that this supports.  I removed it (I think!) from the docs years ago and I'd be fine with bumping up to version 2 and warning people that they have to use new().  I don't know of any CPAN modules that do anything other than call new() to create an object using this module.

If you wanted to hack something together, that would be great.  My preference would be for Moo, but we could always do a Moo conversion down the line.  I have a lot of confidence in our test coverage, so as long as the Travis builds continue to pass, I don't think we need to worry too much about stuff breaking that we don't know about.

**Comment by andrewmoise** [comment]
Okay, I spent some time on this today and uploaded the new work. It's not ready to go quite yet; I would expect that with this amount of changes I've probably changed some behavior and broken some things. It is faster. I misunderstood the profile I was reading: The total time in HTTPBrowser.pm was 128 seconds before I started optimizing. With the current version it's reduced from 128 seconds to 29 seconds.

As I say, there's enough new code that I've probably broken some things. I think things overall actually got a lot cleaner: The main loops that decide on browser, OS, and version now have big if/elsif/elsif/.../elsif/else blocks that control most of their logic, so the logic is easier to follow. Big effects of that are that things get faster, the code is easier to follow, and some of the logic has changed to be more straightforward. Because the logic has changed, some of the tests have broken, but in these cases I would say that the new logic is actually correct. Specifically:

* Mobile Safari on a Blackberry used to set the browser to "Blackberry," now it sets the browser to "Mobile Safari". It still sets the device to Blackberry.

* IEMobile 11 on a Windows Phone used to set properties for chrome, ios, and iphone, because all of those phrases are included in the user agent; now the tests for this situation follow our more usual behavior of setting the tests based on the actual software and hardware and ignoring what the browser is indicating that it's "compatible" with (i.e. we don't set chrome / ios / iphone).

* Safari on a RIM Tablet used to set browser to "BlackBerry", now it sets the browser to "Safari".

* Iceweasel used to be its own browser_string(), now it sets browser_string() to "Firefox", which I think is what most people want.

* Safari on an iPod used to set the "iPhone" test; now it doesn't.

* Opera on a Nintendo DSi used to set browser_string to "Nintendo DSi"; now it says "Opera". The device is still set correctly.

Anyway, take a look and let me know what you think.

**Comment by andrewmoise** [comment]
One other note -- I uploaded profiles of before I started optimizing, and a profile of the current work, in the same repository I put the other one.

**Comment by dougwilson** [comment]
The following UA is now returning "Safari":

> Mozilla/5.0 (PlayBook; U; RIM Tablet OS 2.0.0; en-US) AppleWebKit/535.8+ (KHTML, like Gecko) Version/7.2.0.0 Safari/535.8+

The web browser on the PlayBook is absolutely not related to Safari at all and is very different; many, many things do not work in it that would be expected of a "Safari". This is a case of the PlayBook trying to "pretend" to be Safari. I see you took away all the pretends from IEMobile, so this change doesn't agree with that change, since you went the opposite direction here.

**Comment by dougwilson** [comment]
Basically, the PlayBook browser is as much Safari as Chrome is Safari: they are both just random forks from AppleWebKit at some point; their features differ a lot.

**Comment by andrewmoise** [comment]
Ah, makes sense (I'm just not familiar with the hardware; I thought that was a genuine Safari running on a tablet). How about these?

```
Mozilla/5.0 (BB10; Touch) AppleWebKit/537.35+ (KHTML, like Gecko) Version/10.2
.0.1803 Mobile Safari/537.35+
Mozilla/5.0 (BlackBerry; U; BlackBerry 9800; fr) AppleWebKit/534.1+ (KHTML, li
ke Gecko) Version/6.0.0.246 Mobile Safari/534.1+
```

Are those also a Blackberry-specific browser, or should we still be reporting 'Mobile Safari' for them?

**Comment by dougwilson** [comment]
> Are those also a Blackberry-specific browser, or should we still be reporting 'Mobile Safari' for them?

Those are the same: just random AppleWebKit forks. The one on BB10 is very modern, like on PlayBook, so it's the most similar to what people could _potentially_ call a Safari, but the BB 9800 is much better than BlackBerries of the past (this was BB's first browser based on AppleWebKit), but still pretty bad.

**Comment by andrewmoise** [comment]
Okay. I've restored the previous behavior for Blackberry devices. That also includes setting the "safari" and "mobile_safari" tests on Blackberry devices when they claim to be Safari devices, even though we're reporting the browser as "Blackberry". Does that sound right, or do you think we should change those tests to return 0?

**Comment by oalders** [comment]
@andrewmoise Thanks very much for this.  Not sure if you noticed, but the Travis build is failing https://travis-ci.org/oalders/http-browserdetect/builds/51786847, so there are some issues which still need to be addressed.

**Comment by andrewmoise** [comment]
All of the tests that are currently failing are failing on purpose. For example, IE Mobile on a Windows Phone claims that it's compatible with Chrome, iOS, and iPhone, and so we used to return true for those tests. It looked to me like that wasn't by design, but just an accident of how we did the parsing, so I left the tests broken instead of implementing "bug compatibility" to make those tests true for IEMobile. In an earlier comment I sent a detailed list of tests that I deliberately broke; my feeling is that the tests should change to match the new behavior, but if you look over the list you can let me know what you think.

If you want me to make a bug compatible version that passes all the current tests I can do that. One effect of the new structure is that in most cases it's easy to change a test without breaking anything else; there's a single localized block that defines properties for each browser or situation, so if you want particular changes you can just make them instead of having to struggle with how it's going to affect other situations. I.e. if you guys decide what test behavior you want in a perfect world, it's generally easy to implement now. :-)

All that being said, the current state of this branch is definitely not ready to go yet. There are further organization and speedups to do, the documentation should be updated, and my feeling is that I've probably broken some things that are not exposed by the current test suite (even as complete as it is), so I'd like to add more tests. I just wanted to share the current state of my work with you.

**Comment by andrewmoise** [comment]
There are two different meanings to the word "test" -- that middle paragraph is clearer if it reads:

If you want me to make a bug compatible version that passes all the current tests I can do that. One effect of the new structure is that in most cases it's easy to change browser properties without breaking anything else; there's a single localized block that defines properties for each browser or situation, so if you want particular changes you can just make them instead of having to struggle with how it's going to affect other situations. I.e. if you guys decide what properties you want some user-agent to return in a perfect world, it's generally easy to implement now. :-)

**Comment by oalders** [comment]
Ah, I had a closer look at the tests and I see what you're saying.  Personally, I'm not at all interested in bugwards compatibility.

**Comment by andrewmoise** [comment]
Sounds good to me. I'm happy to do the work of changing the tests, but maybe it'd be better if one of you did it, so that you can give a final look-over to what tests we're changing and catch anything I misunderstood (similar to the Blackberry change Doug caught). I'll add you as collaborators on this branch in case you want to do that, but let me know how you want to proceed.

**Comment by andrewmoise** [comment]
I got impatient. :-) I went ahead and fixed all the tests that seemed obviously to be requiring answers that were not correct. Anything that seemed borderline (e.g. "Iceweasel" vs. "Firefox") I put back to the way it used to be instead of changing the test. I also did some regression testing, taking real user-agents from my log and comparing the answers the master build gives against the answers my branch gives, and as I expected I found a decent amount of stuff that I had broken, and fixed it. I also updated the documentation and did some general cleanup.

I have a lot more confidence now that this branch is going to do what it's supposed to do. The only thing I would still want to do before calling it "good to go" would be to add some tests calling methods in random order, to make sure we're not failing to initialize anything before we inspect it. I think it's likely that there are a few ways in which our "initialized on demand" data can get inspected without getting initialized first.

**Comment by dougwilson** [comment]
Great! I'm heading to sleep now, but I really want to look over the changes (and the adjusted tests) tomorrow to see if I have any further feedback :)

**Comment by andrewmoise** [comment]
Okay, I added tests calling things in random order and fixed a couple of bugs where things weren't properly initialized. As far as I can tell this is ready to merge as long as you guys don't see any issues with it or adjustments to make.

**Comment by oalders** [comment]
Great stuff!  I've been slammed this past week, but I'll get to this as soon as I can if @dougwilson doesn't beat me to it. :)

**Comment by dougwilson** [comment]
Sorry for the unintentional delay from me :) So my primary judgement is typically based on changes to the `t/useragents.json` file. I don't have any objections to the changes currently made in there :)

**Comment by andrewmoise** [comment]
No worries, there's no rush. And yes, having the test suite is excellent.

**Comment by oalders** [comment]
:+1:

**Comment by oalders** [comment]
New version has now been released. Thanks for all of your work on this!

**Comment by andrewmoise** [comment]
No worries, happy to help. I've made a couple of other fixes also; I'll make separate pull requests for them.

**Pull request merged**
