### PR TITLE
Misc new features

### PR DESCRIPTION
**Pull request by andrewmoise**
New features and fixes along the lines I mentioned earlier. The short summary is:

* Less backwards compatibility; Blackberry stops having "Safari" properties, Android stops having "Linux" properties, etc.

* Implement more modern engine detection and engine version detection

* Make the lib / robot handling a bit more consistent, adding a "lib" test and making java a robot

* Documentation reorganization and updates

### CODE REVIEW

**Comment by andrewmoise** [comment]
Also, while I was working I noticed that the interface is inconsistent in places:

* We have robot_name() and device_name() but browser_string() and os_string() ("name" versus "string" mean the same thing but we're using two different words)

* device() as a tightly defined list of IDs, with device_name() as a more human-readable and flexible output, is an excellent idea which isn't being applied to browsers or OSs

* The way of returning version numbers for OS, browser, and engine is inconsistent

I sketched out in the TODO file how I would approach making all of this consistent without breaking existing code that relies on the existing interface. We can do it without too much difficulty: Just add a browser() method and an os() method, and change device_name() to device_string() and robot_name() to robot_string() (with the old names as deprecated options). Once we did that, everything in the interface would look the same so it's simple to understand.

For version numbers, my feeling would be to return "$major.$minor" by default, but have browser_version() (or whatever) take an optional argument that requests some other format. But, there are a lot of different possible ways to do it; mainly we should figure out which one we want and make sure to do it for browser, OS, and engine.

Let me know what you think; this type of change isn't something I would start spending any time on without checking how you feel about it, but I do think it'd be a good idea.

**Comment by oalders** [comment]
:+1:

**Comment by oalders** [comment]
@andrewmoise What you have sketched out in the TODO file looks good to me.  This module has grown organically over time, so more consistency in the interface would be a very good thing.  :)  Thanks for all of your work on this!

**Comment by andrewmoise** [comment]
Okay, sounds excellent. Don't sweat it; I like doing this stuff. I don't get a chance to do too much engineering now. Me working on this is me playing hooky from my actual responsibilities. :-)

**Pull request merged**
